server:
    port: 8763

# 需要外部化的配置
config:
    server-ip: 127.0.0.1
    server-develop-ip: 192.168.200.51
    mysql:
        dbname: etcc_biz
        username: yjanquan
        password: yjanquan
    rabbitmq:
        username: dev
        password: dev@123456
    redis:
        database: 2
logging:
    level:
        #        tk.mybatis: DEBUG
        com.etcc.biz: DEBUG

spring:
    application:
        name: etcc-biz
    flyway:
        baseline-on-migrate: true
        enabled: true
    freemarker:
        checkTemplateLocation: false    
    cloud:
        nacos:
            discovery:
                server-addr: ${config.server-ip}:8848
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: ALWAYS
    datasource:
        name: ${config.mysql.dbname}
        url: jdbc:mysql://${config.server-develop-ip}:3306/${config.mysql.dbname}?useUnicode=true&characterEncoding=UTF8
        username: ${config.mysql.username}
        password: ${config.mysql.password}
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        database: ${config.redis.database}
        host: ${config.server-develop-ip}
#        password: 192.168.200.51
        port: 6379
        timeout: 2000
        #        pool:
        #        max-active: 20
        lettuce:
            pool:
                min-idle: 0
                max-idle: 8
                max-wait: -1ms
                max-active: 8
    rabbitmq:
        host: ${config.server-develop-ip}
        port: 5672
        username: ${config.rabbitmq.username}
        password: ${config.rabbitmq.password}
    sleuth:
        enabled: true
        http:
            legacy:
                enabled: true

#mybatis-plus
mybatis-plus:
    mapper-locations: classpath*:com/etcc/**/mapper/xml/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.etcc.*.entity
    global-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 2
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: 1
        #驼峰下划线转换
        db-column-underline: true
        #刷新mapper 调试神器
        refresh-mapper: true
        #数据库大写下划线转换
        #capital-mode: true
        # Sequence序列接口实现类配置
        #key-generator: com.baomidou.mybatisplus.extension.incrementer.OracleKeyGenerator
        #自定义填充策略接口实现
        #meta-object-handlers: com.baomidou.springboot.xxx
        #自定义SQL注入器
        #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
        db-config:
            #逻辑删除配置
            logic-delete-value: 1 # 逻辑已删除值(默认为 1)
            logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true


#sample:
#    zipkin:
#        # When enabled=false, traces log to the console. Comment to send to zipkin
#        enabled: false

# 必须配置
feign:
    client:
        default:
            #这里时间一定要调长，否则feign客户端会报ReadTimeOut  服务端报Error parsing HTTP request header
            connectTimeout: 60000
            readTimeout: 60000
    httpclient:
        enabled: false
    okhttp:
        enabled: true

ribbon:
    eureka:
        enabled: true
    ReadTimeout: 100000
    ConnectTimeout: 100000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: false

hystrix:
    threadpool:
        default:
            coreSize: 1000 ##并发执行的最大线程数，默认10
            maxQueueSize: 1000 ##BlockingQueue的最大队列数
            queueSizeRejectionThreshold: 500 ##maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 110000

auth:
    service-id: etcc-auth
    user:
        token-header: Authorization
        secretKey: private-secret
    client:
        id: etcc-biz
        secret: 123456
        token-header: x-client-token
        expire: 14400


#management:
#    endpoints:
#        web:
#            exposure:
#                include: ["health","info"]

call:
    url:
    # 创智单方通话url
        cp: http://120.27.126.63:10080/call/cp
    # 创智多方通话url
        cf: http://120.27.126.63:10080/call/cf
    # 创智分机状态查询接口
        peer: http://120.27.126.63:10080/peers/status
    # 创智通话录音文件根目录
        file: http://120.27.126.63:8089/files/

file:
    server:
        url: http://192.168.200.51:8089/fileserver/file/
    # absolute-path: /home/admin/etcc_file
    absolute-path: D:/file
    relative-path: etcc_template