server:
    port: 8768
    servlet: 
        context-path: /xxl-job-admin

# 需要外部化的配置
config:
    server-ip: 127.0.0.1
    develop-server-ip: 127.0.0.1
    mysql:
        dbname: etcc_job
        username: yjanquan
        password: yjanquan

spring:
    application:
        name: etcc-job
    cloud:
        nacos:
            discovery:
                server-addr: ${config.server-ip}:8848
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: ALWAYS
    datasource:
        name: etcc-job
        url: jdbc:mysql://${config.develop-server-ip}:3306/${config.mysql.dbname}?Unicode=true&characterEncoding=UTF-8
        username: ${config.mysql.username}
        password: ${config.mysql.password}
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        # filters: stat
        # maxActive: 20
        # initialSize: 1
        # maxWait: 60000
        # minIdle: 1
        # timeBetweenEvictionRunsMillis: 60000
        # minEvictableIdleTimeMillis: 300000
        # validationQuery: select 'x'
        # testWhileIdle: true
        # testOnBorrow: false
        # testOnReturn: false
        # poolPreparedStatements: true
        # maxOpenPreparedStatements: 20

mybatis: 
    mapper-locations: classpath*:/mybatis-mapper/*Mapper.xml